name: Deployment Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Build-RC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Commit Stage Tests + Package
        run: mvn -B package

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/subs-buddy:rc

      - name: Deploy On Test Environment
        run: >
          echo "Deploying on test environment..."

      - name: Acceptance Stage Tests
        run: >
          echo "Running acceptance tests againts test environment..."