name: NightWatch Node

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 20.11.0 ]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - run: npm ci
        working-directory: ./src/test/nightwatch
      - run: mkdir -p screens logs
      - run: sudo apt-get install xvfb
      - name: Run Nightwatch tests
        env:
          SUBS_BUDDY_URL: ${{secrets.SUBS_BUDDY_URL}}
        run: xvfb-run --auto-servernum npm test -- --env chrome
        working-directory: ./src/test/nightwatch